
## Collecting Data from API

Opening conda prompt:

1. cd /d D:\crypto_trading

2. conda activate cryptotrading

3. jupyter notebook

https://developers.binance.com/docs/binance-spot-api-docs

https://www.bitmex.com/app/apiOverview

In [1]:
# import necessary files
import logging
from exchanges.binance import BinanceClient
from exchanges.coinbase import CoinbaseClient
from database import Hdf5Client
from utils.time_convertor import *
import pandas as pd
import numpy as np
import time

#strategies
import strategies.obv
import strategies.ichimoku as ic

In [2]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)
pd.set_option("display.width", 5000)
pd.set_option('display.expand_frame_repr', False)  # prevent wrapping of DataFrame

In [3]:
h5_db= Hdf5Client("Binance")
data= h5_db.get_data("BTCUSDT", from_time= 0, to_time= int(time.time() * 1000))

In [4]:
#import and format the data
data= resample_timeframe(data, "15m")
data

                          open       high        low      close       volume
timestamp
2025-03-26 06:15:00   87491.02   87587.24   87491.03   87565.05    60.468010
2025-03-26 06:30:00   87565.04   87768.00   87565.05   87767.99   184.820200
2025-03-26 06:45:00   87729.25   87923.92   87729.25   87909.07   166.300280
2025-03-26 07:00:00   87881.90   87953.63   87774.36   87841.12   212.873040
2025-03-26 07:15:00   87841.11   88030.46   87786.69   88009.79   137.899660
2025-03-26 07:30:00   87972.22   88259.65   87972.22   88211.29   464.476420
2025-03-26 07:45:00   88186.22   88275.00   88145.87   88140.45   238.222820
2025-03-26 08:00:00   88132.30   88200.00   88027.05   88053.83   146.987880
2025-03-26 08:15:00   88053.83   88149.79   88004.96   88041.26   113.948560
2025-03-26 08:30:00   88041.26   88086.96   88034.62   88047.37    64.934720
2025-03-26 08:45:00   87977.87   88047.37   87888.00   87959.73   199.242150
2025-03-26 09:00:00   87959.73   88000.00   87887.12   87891.30   122.453160
2025-03-26 09:15:00   87885.76   87997.70   87853.99   87969.25   121.379100
2025-03-26 09:30:00   87950.00   88056.61   87939.13   87976.19    76.181560
2025-03-26 09:45:00   87943.92   87977.40   87891.04   87939.99    73.083680
2025-03-26 10:00:00   87939.99   88041.48   87940.00   88025.00    82.152550
2025-03-26 10:15:00   88025.00   88228.83   88025.00   88156.46   182.160900
2025-03-26 10:30:00   88156.45   88259.81   88103.77   88104.87   185.354880
2025-03-26 10:45:00   88104.86   88250.00   88104.86   88208.47   106.537080
2025-03-26 11:00:00   88208.46   88242.00   88149.31   88230.00   117.256540
2025-03-26 11:15:00   88223.01   88241.94   88125.17   88155.57   304.195910
2025-03-26 11:30:00   88153.22   88192.94   87969.29   87987.25   370.129750
2025-03-26 11:45:00   87949.32   88056.05   87960.00   87954.96   148.735770
2025-03-26 12:00:00   87952.11   88000.00   87845.40   87960.98   154.941730
2025-03-26 12:15:00   87915.09   87979.63   87698.23   87783.49   230.142340
2025-03-26 12:30:00   87763.41   87817.55   87613.88   87699.88   273.118720
2025-03-26 12:45:00   87672.80   87856.78   87644.84   87813.17   167.196270
2025-03-26 13:00:00   87762.00   87813.17   87650.76   87660.57   148.501210
2025-03-26 13:15:00   87599.42   87660.57   87478.97   87493.55   252.777020
2025-03-26 13:30:00   87474.40   87886.68   87407.54   87800.00   471.884880
2025-03-26 13:45:00   87800.00   87920.08   86856.83   86841.31   809.242730
2025-03-26 14:00:00   86738.40   87294.05   86841.30   86974.30   571.749080
2025-03-26 14:15:00   86974.10   87062.64   86486.03   86699.51   653.774230
2025-03-26 14:30:00   86587.72   86815.82   86591.39   86570.44   420.540380
2025-03-26 14:45:00   86462.75   86978.27   86473.03   86773.14   294.893830
2025-03-26 15:00:00   86738.23   86998.00   86773.14   86858.66   269.260790
2025-03-26 15:15:00   86769.83   86871.36   86594.00   86640.00   332.654410
2025-03-26 15:30:00   86634.00   86909.34   86640.00   86851.76   203.476270
2025-03-26 15:45:00   86822.00   87018.87   86657.83   86752.52   382.947210
2025-03-26 16:00:00   86605.12   86845.17   86610.41   86750.00   189.351190
2025-03-26 16:15:00   86692.03   86955.77   86628.85   86955.76   144.581540
2025-03-26 16:30:00   86924.70   87058.40   86705.26   86694.78   177.520660
2025-03-26 16:45:00   86689.10   86831.67   86447.81   86513.99   239.751690
2025-03-26 17:00:00   86480.01   86774.54   86513.99   86727.68   147.550860
2025-03-26 17:15:00   86658.29   86727.69   86491.06   86617.01   185.087160
2025-03-26 17:30:00   86600.69   86829.88   86504.37   86691.33   131.288610
2025-03-26 17:45:00   86685.98   86780.00   86506.00   86569.99   104.075650
2025-03-26 18:00:00   86565.66   86747.95   86562.00   86684.78    85.831130
2025-03-26 18:15:00   86644.41   86750.01   86594.02   86642.00    88.614990
2025-03-26 18:30:00   86619.56   86750.00   86519.99   86500.01    96.001820
2025-03-26 18:45:00   86500.00   86518.19   86228.18   86198.53   292.376430
2025-03-26 19:00:00   86198.15   86358.70   85885.72   85937.48   355.373540
2025-03-26 19:15:00   85860.00   86373.62   85875.66   86130.44   296.058000
2025-03-26 19:30:00   86130.44   86516.14   86130.44   86489.14   153.198510
2025-03-26 19:45:00   86489.13   86800.77   86489.13   86567.19   320.298110
2025-03-26 20:00:00   86520.10   87009.55   86567.18   86920.00   237.746230
2025-03-26 20:15:00   86859.99   87329.26   86875.98   87228.84   276.032720
2025-03-26 20:30:00   87187.25   87404.34   87187.26   87293.27   207.089490
2025-03-26 20:45:00   87293.27   87349.06   87152.52   87280.00   175.189650
2025-03-26 21:00:00   87277.23   87302.00   87112.83   87212.01    84.150890
2025-03-26 21:15:00   87201.26   87239.14   86978.26   87058.13   185.715700
2025-03-26 21:30:00   86990.52   87076.99   86791.05   87076.98   171.738730
2025-03-26 21:45:00   87076.99   87227.43   87065.58   87109.65    99.760690
2025-03-26 22:00:00   86963.48   87147.92   86898.01   86938.38   103.174150
2025-03-26 22:15:00   86916.00   86989.68   86765.19   86807.99   100.023610
2025-03-26 22:30:00   86807.99   86971.70   86808.00   86892.36    87.610880
2025-03-26 22:45:00   86881.39   87027.90   86832.01   86829.48    57.067390
2025-03-26 23:00:00   86826.00   86900.00   86675.60   86694.09    88.013480
2025-03-26 23:15:00   86694.09   86791.81   86563.69   86682.01    96.405970
2025-03-26 23:30:00   86682.00   86892.00   86682.00   86864.89    76.902050
2025-03-26 23:45:00   86809.48   86952.20   86850.92   86909.17    72.432820
2025-03-27 00:00:00   86909.17   86967.65   86883.24   86901.33    77.321150
2025-03-27 00:15:00   86843.90   87121.17   86803.24   87120.37   111.485040
2025-03-27 00:30:00   87079.65   87248.06   87053.03   87108.69   125.445860
2025-03-27 00:45:00   87096.77   87308.00   87108.70   87285.29   125.016280
2025-03-27 01:00:00   87283.75   87419.27   87242.72   87287.68   187.331320
2025-03-27 01:15:00   87248.00   87391.00   87184.96   87354.81    81.440960
2025-03-27 01:30:00   87318.00   87362.31   87194.17   87301.84    84.516630
2025-03-27 01:45:00   87277.99   87519.38   87254.71   87378.87   130.916870
2025-03-27 02:00:00   87338.79   87587.00   87353.00   87520.48    96.572950
2025-03-27 02:15:00   87508.42   87685.88   87487.54   87596.95   136.246030
2025-03-27 02:30:00   87572.02   87678.57   87541.00   87669.53   123.694050
2025-03-27 02:45:00   87642.35   87756.39   87562.47   87575.39   118.169510
2025-03-27 03:00:00   87569.17   87665.99   87475.24   87573.60    94.430230
2025-03-27 03:15:00   87532.60   87573.60   87436.81   87543.45   119.590290
2025-03-27 03:30:00   87539.72   87669.46   87543.44   87602.01   175.492250
2025-03-27 03:45:00   87591.28   87675.00   87602.01   87670.18   103.494800
2025-03-27 04:00:00   87653.88   87691.34   87431.64   87482.29   148.845710
2025-03-27 04:15:00   87482.30   87599.99   87445.78   87577.72    89.383810
2025-03-27 04:30:00   87577.71   87607.11   87438.69   87470.58    86.399590
2025-03-27 04:45:00   87470.58   87532.00   87458.10   87521.61    65.300060
2025-03-27 05:00:00   87473.31   87521.60   87425.09   87470.17   148.738900
2025-03-27 05:15:00   87470.16   87506.13   87370.66   87439.99   105.902620
2025-03-27 05:30:00   87405.61   87440.00   87352.72   87353.88   144.260620
2025-03-27 05:45:00   87353.87   87390.02   87264.38   87314.72    99.122180
2025-03-27 06:00:00   87288.31   87455.58   87301.76   87455.57    96.971810
2025-03-27 06:15:00   87455.57   87524.69   87416.34   87482.52   120.448640
2025-03-27 06:30:00   87482.51   87547.60   87440.07   87418.00    92.646710
2025-03-27 06:45:00   87417.99   87422.01   87280.01   87352.68   111.064230
2025-03-27 07:00:00   87352.67   87389.00   87254.72   87350.50   118.156030
2025-03-27 07:15:00   87350.49   87408.39   87277.08   87333.99    86.792350
2025-03-27 07:30:00   87333.99   87439.30   87285.79   87302.02   156.009110
2025-03-27 07:45:00   87288.89   87400.00   87298.01   87399.99   105.075530
2025-03-27 08:00:00   87370.21   87493.02   87269.71   87359.99   170.249350
2025-03-27 08:15:00   87323.39   87462.48   87323.40   87410.74    89.425770
2025-03-27 08:30:00   87410.74   87597.60   87409.00   87481.40   156.284940
2025-03-27 08:45:00   87456.27   87481.40   87334.03   87434.82   123.138140
2025-03-27 09:00:00   87409.53   87512.99   87406.18   87482.88   149.895730
2025-03-27 09:15:00   87474.62   87520.00   87430.66   87464.39    78.896700
2025-03-27 09:30:00   87457.33   87537.74   87428.13   87462.80   103.031170
2025-03-27 09:45:00   87462.80   87516.95   87416.14   87415.56   121.251070
2025-03-27 10:00:00   87400.33   87597.60   87411.50   87479.75   139.628070
2025-03-27 10:15:00   87442.15   87532.54   87438.34   87507.68    65.316640
2025-03-27 10:30:00   87507.68   87550.00   87435.01   87425.12    68.139100
2025-03-27 10:45:00   87364.60   87425.12   87145.72   87195.59   255.947580
2025-03-27 11:00:00   87150.55   87316.29   87186.40   87179.30   143.717910
2025-03-27 11:15:00   87179.30   87250.26   86912.94   86946.01   230.396890
2025-03-27 11:30:00   86870.72   87074.08   86870.72   86904.37   173.507220
2025-03-27 11:45:00   86888.00   86988.78   86815.98   86943.52   126.948670
2025-03-27 12:00:00   86830.71   87041.26   86808.69   87003.05   171.843520
2025-03-27 12:15:00   86979.29   87060.09   86902.52   86952.28   140.471930
2025-03-27 12:30:00   86940.00   87110.10   86891.21   86892.41   177.877470
2025-03-27 12:45:00   86892.40   86927.67   86738.52   86761.05   175.513170
2025-03-27 13:00:00   86721.70   86861.71   86660.01   86645.74   165.400810
2025-03-27 13:15:00   86618.05   86708.00   86200.03   86341.24   517.872720
2025-03-27 13:30:00   86238.00   86518.07   85860.04   86019.99   915.563150
2025-03-27 13:45:00   85965.05   86486.22   85970.88   86383.83  1012.091140
2025-03-27 14:00:00   86356.92   86750.00   86189.19   86443.39   798.898610
2025-03-27 14:15:00   86443.40   86647.86   86393.33   86627.35   417.066850
2025-03-27 14:30:00   86627.35   87202.48   86565.94   87055.72   948.108690
2025-03-27 14:45:00   86909.11   87321.56   86919.39   87297.33   545.395600
2025-03-27 15:00:00   87252.00   87418.80   87146.00   87386.66   418.263620
2025-03-27 15:15:00   87361.53   87575.00   87321.34   87278.30   438.198580
2025-03-27 15:30:00   87208.02   87278.31   86900.00   86865.97   396.254090
2025-03-27 15:45:00   86862.22   87087.57   86781.99   86974.07   301.947320
2025-03-27 16:00:00   86928.28   87212.00   86938.41   87082.27   198.964840
2025-03-27 16:15:00   87075.45   87271.43   87027.54   87012.39   126.695910
2025-03-27 16:30:00   87001.77   87148.00   86994.44   87141.30   156.957500
2025-03-27 16:45:00   87124.01   87162.00   86831.58   86835.24   189.081610
2025-03-27 17:00:00   86835.24   87032.00   86835.24   86961.76   167.858510
2025-03-27 17:15:00   86943.43   87074.19   86875.27   86867.00   175.940110
2025-03-27 17:30:00   86863.63   86978.10   86814.81   86978.09   121.306440
2025-03-27 17:45:00   86969.39   87150.95   86936.00   86913.05   131.386860
2025-03-27 18:00:00   86898.00   87136.01   86910.01   87132.31   100.713820
2025-03-27 18:15:00   87110.00   87150.00   86986.71   87047.90   134.798870
2025-03-27 18:30:00   87047.90   87374.00   87047.91   87343.39   137.150320
2025-03-27 18:45:00   87336.05   87420.00   87232.47   87206.52   100.433310
2025-03-27 19:00:00   87198.11   87357.14   87150.46   87350.00    80.813800
2025-03-27 19:15:00   87339.62   87429.21   87286.30   87364.00   109.148890
2025-03-27 19:30:00   87307.85   87398.49   87285.43   87306.96    86.833320
2025-03-27 19:45:00   87246.68   87312.95   87086.17   87060.41   197.004570
2025-03-27 20:00:00   87054.00   87087.85   86962.07   86957.74   158.792670
2025-03-27 20:15:00   86943.04   87282.24   86947.45   87205.84   159.240360
2025-03-27 20:30:00   87205.84   87315.98   87182.58   87315.43    91.237540
2025-03-27 20:45:00   87315.44   87346.07   87252.22   87307.57    45.192420
2025-03-27 21:00:00   87307.56   87354.99   87247.90   87299.99    63.146460
2025-03-27 21:15:00   87299.99   87464.10   87284.26   87387.25   106.093770
2025-03-27 21:30:00   87371.91   87728.27   87371.91   87633.34   245.557590
2025-03-27 21:45:00   87633.33   87638.38   87519.82   87568.68    73.905800
2025-03-27 22:00:00   87559.80   87600.00   87413.99   87416.76    97.589420
2025-03-27 22:15:00   87403.28   87490.68   87362.65   87383.93    71.544470
2025-03-27 22:30:00   87383.93   87425.68   87336.80   87348.73    56.340920
2025-03-27 22:45:00   87341.09   87433.97   87325.41   87350.71    37.971940
2025-03-27 23:00:00   87336.96   87361.07   87182.01   87190.01    85.050770
2025-03-27 23:15:00   87184.00   87291.50   87190.01   87291.50    63.234210
2025-03-27 23:30:00   87269.04   87339.63   87144.75   87155.15    67.882410
2025-03-27 23:45:00   87141.30   87259.83   87128.01   87232.01    57.345200
2025-03-28 00:00:00   87230.20   87251.73   87021.75   87064.73   109.248440
2025-03-28 00:15:00   87060.46   87123.89   86973.65   86970.00    87.927850
2025-03-28 00:30:00   86929.58   87209.57   86970.00   87209.57   110.870610
2025-03-28 00:45:00   87190.29   87402.08   87155.42   87354.01   130.134830
2025-03-28 01:00:00   87323.23   87373.98   87166.09   87163.84   126.518980
2025-03-28 01:15:00   87137.67   87218.63   87131.00   87169.58    65.292600
2025-03-28 01:30:00   87142.48   87515.67   87129.70   87505.32   186.804760
2025-03-28 01:45:00   87453.47   87505.32   87206.67   87230.29   137.810620
2025-03-28 02:00:00   87230.30   87308.00   87177.06   87232.01    84.754070
2025-03-28 02:15:00   87232.01   87327.98   87232.01   87247.94    63.251830
2025-03-28 02:30:00   87186.06   87249.04   87074.39   87090.18   123.345070
2025-03-28 02:45:00   87062.44   87169.70   86961.11   86987.77   117.380350
2025-03-28 03:00:00   86964.85   87018.36   86807.18   86867.93   205.947750
2025-03-28 03:15:00   86815.99   86943.49   86801.93   86800.00   162.341200
2025-03-28 03:30:00   86800.00   86891.40   86800.00   86844.14    91.272110
2025-03-28 03:45:00   86844.14   86859.43   86790.83   86787.16   108.819380
2025-03-28 04:00:00   86787.16   86832.64   86775.85   86774.43    93.960180
2025-03-28 04:15:00   86742.95   86783.56   86679.25   86712.09   158.590880
2025-03-28 04:30:00   86656.29   86712.09   86221.05   86251.57   716.910950
2025-03-28 04:45:00   86167.85   86363.63   85985.53   86305.38   506.218920
2025-03-28 05:00:00   86160.37   86305.38   86068.01   86075.93   252.308380
2025-03-28 05:15:00   86038.00   86200.69   86002.83   85975.71   221.382090
2025-03-28 05:30:00   85935.08   86065.99   85895.28   85908.79   277.221390
2025-03-28 05:45:00   85880.83   86204.81   85832.66   86059.02   274.443060
2025-03-28 06:00:00   85978.56   86250.00   86037.35   86209.71   201.606910
2025-03-28 06:15:00   86172.56   86224.50   85925.25   86003.58   165.654640
2025-03-28 06:30:00   85983.51   86018.87   85849.08   85852.63   216.357770
2025-03-28 06:45:00   85852.63   85969.99   85690.12   85719.27   427.381920
2025-03-28 07:00:00   85661.46   85888.60   85689.22   85709.90   220.318010
2025-03-28 07:15:00   85709.90   85821.85   85588.90   85605.58   310.807430
2025-03-28 07:30:00   85580.91   85628.03   85232.99   85260.44  1117.516850
2025-03-28 07:45:00   85224.17   85360.00   85182.76   85212.99   510.416900
2025-03-28 08:00:00   85161.70   85441.25   85212.98   85281.69   473.677000
2025-03-28 08:15:00   85271.43   85381.73   85089.99   85083.41   354.120410
2025-03-28 08:30:00   85058.88   85206.41   85058.82   85174.89   304.622690
2025-03-28 08:45:00   85163.81   85409.72   85174.88   85213.87   257.158600
2025-03-28 09:00:00   85185.04   85246.61   85082.10   85061.00   201.475360
2025-03-28 09:15:00   85061.00   85320.00   85034.93   85320.00   286.818570
2025-03-28 09:30:00   85272.31   85417.47   85219.99   85209.83   384.162110
2025-03-28 09:45:00   85168.47   85209.83   85093.48   85148.00   426.110180
2025-03-28 10:00:00   85111.64   85250.79   85022.00   85165.27   337.819320
2025-03-28 10:15:00   85118.96   85240.21   85081.30   85240.00   194.290030
2025-03-28 10:30:00   85182.67   85240.00   85109.29   85120.41   172.188530
2025-03-28 10:45:00   85082.29   85120.41   84896.00   84941.49   284.316680
2025-03-28 11:00:00   84921.48   85024.48   84843.41   84817.61   225.370650
2025-03-28 11:15:00   84800.00   85220.79   84817.61   85101.20   687.184820
2025-03-28 11:30:00   85072.66   85206.53   84982.01   85065.06   179.830250
2025-03-28 11:45:00   85057.50   85255.26   85015.92   85255.26   181.614570
2025-03-28 12:00:00   85235.48   85282.52   85144.06   85174.74    96.002700
2025-03-28 12:15:00   85152.44   85433.96   85148.00   85375.58   174.160310
2025-03-28 12:30:00   85111.14   85609.74   84893.46   85116.94   725.446710
2025-03-28 12:45:00   85059.43   85228.24   85045.30   85028.27   149.805470
2025-03-28 13:00:00   85016.90   85350.00   84997.03   85350.00   212.232400
2025-03-28 13:15:00   85321.73   85546.88   85293.57   85333.15   252.052860
2025-03-28 13:30:00   85222.44   85575.68   85152.56   85304.11   355.080450
2025-03-28 13:45:00   85223.92   85311.33   84944.67   84994.00   497.724890
2025-03-28 14:00:00   84896.35   85120.19   84338.00   84446.66  1089.194860
2025-03-28 14:15:00   84405.40   84660.06   84321.73   84361.14   841.149410
2025-03-28 14:30:00   84356.00   84472.00   84194.50   84405.20   784.248350
2025-03-28 14:45:00   84318.07   84418.73   84154.00   84172.01   616.460360
2025-03-28 15:00:00   84117.36   84367.48   84019.55   84305.39  1058.823960
2025-03-28 15:15:00   84227.93   84392.61   84086.22   84241.25   559.433960
2025-03-28 15:30:00   84206.00   84530.45   84228.27   84286.01   540.631920
2025-03-28 15:45:00   84261.81   84398.17   84075.47   84051.16   430.189710
2025-03-28 16:00:00   84049.42   84217.61   83924.00   83891.33   361.359990
2025-03-28 16:15:00   83872.74   84034.00   83765.27   83937.16   342.436370
2025-03-28 16:30:00   83924.74   84044.81   83893.67   83919.97   207.374470
2025-03-28 16:45:00   83867.20   83961.15   83788.02   83794.73   241.060480
2025-03-28 17:00:00   83760.00   83901.19   83589.69   83658.32   361.890970
2025-03-28 17:15:00   83612.00   83952.20   83620.99   83751.21   299.092410
2025-03-28 17:30:00   83685.08   83930.00   83685.09   83743.46   253.445800
2025-03-28 17:45:00   83714.79   84010.41   83730.88   84008.45   200.436720
2025-03-28 18:00:00   83971.69   84169.52   84008.46   84076.35   280.608570
2025-03-28 18:15:00   84076.35   84152.84   83818.03   83821.40   188.271170
2025-03-28 18:30:00   83807.56   83953.05   83752.13   83840.00   118.919420
2025-03-28 18:45:00   83819.72   83893.48   83730.44   83880.00   168.070070
2025-03-28 19:00:00   83866.63   83893.48   83706.85   83761.99   210.941320
2025-03-28 19:15:00   83737.43   83793.32   83648.42   83793.32   173.072660
2025-03-28 19:30:00   83772.00   83803.62   83686.89   83676.07   189.001740
2025-03-28 19:45:00   83676.08   83893.48   83676.08   83790.73   261.880960
2025-03-28 20:00:00   83764.48   83935.67   83750.00   83829.86   359.419290
2025-03-28 20:15:00   83810.07   83990.79   83829.86   83893.00   489.800170
2025-03-28 20:30:00   83892.99   84160.38   83888.00   84066.04   247.627500
2025-03-28 20:45:00   84018.86   84076.00   83747.59   83794.41   174.187370
2025-03-28 21:00:00   83794.41   84012.00   83710.00   83982.53    89.090920
2025-03-28 21:15:00   83965.36   84074.49   83821.11   84007.99    64.656840
2025-03-28 21:30:00   84007.99   84110.36   84000.00   84029.81    76.458140
2025-03-28 21:45:00   84008.24   84052.30   83860.01   84052.29    65.570950
2025-03-28 22:00:00   84052.29   84259.39   84052.29   84224.01   122.534800
2025-03-28 22:15:00   84201.01   84264.94   84142.43   84235.98    87.354770
2025-03-28 22:30:00   84235.98   84343.93   84235.98   84315.36   105.910100

## Testing out strategies:

##### Ichimoku:

In [5]:
data= ic.backtest(data, 9, 26)
data

                          open       high        low      close      volume  tenkan_sen   kijun_sen  senkou_span_a  senkou_span_b  chikou_span  tenkan_minus_kijun  prev_tenkan_minus_kijun  signal       pnl
timestamp
2025-03-27 10:30:00   87507.68   87550.00   87435.01   87425.12    68.13910   87465.815   87430.915     87357.3675      86816.025     86961.76              34.900                  -12.530       1       NaN
2025-03-30 08:45:00   83265.01   83406.14   83265.02   83378.09    81.20280   83239.595   83186.245     82820.4075      82460.515     82834.39              53.350                  -78.525       1 -0.046291
2025-03-31 00:30:00   81927.68   81992.78   81408.00   81361.51   471.41848   82082.850   82158.055     82550.8625      82797.170     82071.99             -75.205                   55.685      -1 -0.024186
2025-03-31 09:30:00   81490.12   81577.82   81376.01   81496.80   287.99958   81819.875   81840.790     81976.9125      82200.940     83339.99             -20.915                    2.845      -1 -0.001663
2025-04-04 07:00:00   83054.72   83567.00   83054.73   83522.84   393.02241   83108.720   83091.180     82727.7325      82365.140     82329.99              17.540                  -57.110       1 -0.024860
2025-04-05 03:00:00   83957.88   83976.61   83819.42   83822.87   123.74655   84026.800   83961.780     83618.3475      83231.580     83783.02              65.020                  -73.205       1  0.003592
2025-04-11 00:15:00   79630.48   79722.78   79506.29   79454.96   163.43161   79667.615   79669.505     79790.5825      80485.170     81102.00              -1.890                   46.835      -1 -0.052109
2025-04-13 01:00:00   85466.82   85800.00   85444.10   85777.71   195.06800   85416.515   85369.875     84626.1425      84348.590     84461.28              46.640                  -67.800       1 -0.079577
2025-04-13 12:15:00   84577.79   84700.00   84273.99   84283.01   223.30036   84552.435   84611.925     85162.9175      85256.720     84730.00             -59.490                   17.810      -1 -0.017425
2025-04-13 19:30:00   84471.69   84563.90   83179.30   83530.86   880.56711   84061.350   84084.760     84567.2725      85186.995     84391.30             -23.410                  426.700      -1  0.008924
2025-04-14 00:15:00   84097.62   85129.69   84146.00   84764.47   746.55341   84149.365   84094.210     84288.1125      84246.110     84624.21              55.155                 -316.545       1 -0.014768
2025-04-14 23:00:00   84483.86   84679.72   84483.87   84613.59    74.67010   84713.365   84729.180     84808.3600      84808.360     85802.00             -15.815                    9.940      -1 -0.001780
2025-04-15 13:30:00   85787.44   86100.00   85665.99   86057.37   650.36912   85753.625   85745.075     85424.6375      85128.540     84168.17               8.550                  -62.000       1 -0.017063
2025-04-16 05:30:00   83322.33   83476.00   83237.92   83464.91   206.03555   83529.960   83553.005     84143.1250      85072.940     84008.87             -23.045                   54.490      -1 -0.030125
2025-04-16 21:45:00   84466.23   84663.59   84466.24   84545.36   108.00118   84408.595   84390.605     84441.6675      84211.140     83974.16              17.990                 -131.450       1 -0.012945
2025-04-16 23:45:00   84099.01   84180.00   84026.30   84030.38   172.41583   84344.945   84390.605     84825.1125      84316.585     84604.00             -45.660                    1.760      -1 -0.006091
2025-04-17 22:00:00   85018.83   85093.40   84941.85   85043.90    81.91717   84994.525   84936.540     84296.5900      84432.945     84675.37              57.985                  -35.950       1 -0.012061
2025-04-18 01:15:00   85020.00   85132.08   84970.30   85132.08   104.48441   84941.730   84852.610     84876.8100      84641.260     84654.68              89.120                 -102.760       1  0.001037
2025-04-20 02:15:00   85257.44   85285.30   85208.75   85221.18    37.75616   85212.280   85205.705     85182.0825      85195.965     84647.30               6.575                  -20.190       1  0.001047
2025-04-21 14:15:00   87626.04   88409.99   87604.66   88366.04  1840.72929   87605.935   87554.990     87467.6250      86129.870     87367.92              50.945                   -1.745       1  0.036902
2025-04-23 18:00:00   93872.80   94219.93   93860.70   94059.31   300.83183   93566.730   93320.755     93858.0300      93574.455     93625.67             245.975                  -47.295       1  0.064428
2025-04-26 02:30:00   94857.53   95157.73   94849.54   95086.95    89.62520   94870.400   94846.665     94981.8950      94629.595     94355.96              23.735                  -49.490       1  0.010925
2025-04-27 12:00:00   93885.00   93926.85   93826.09   93830.50    67.82271   94003.045   94078.970     94269.7600      94539.800     94364.37             -75.925                    5.465      -1 -0.013214
2025-04-29 21:00:00   94820.04   94968.00   94678.18   94676.66   144.09551   95063.510   95069.085     94945.2450      94839.015     94745.54              -5.575                   65.150      -1 -0.009018
2025-04-30 10:45:00   94960.72   95022.49   94908.01   94946.52   124.15177   94821.465   94818.620     94650.8900      94601.270     94036.62               2.845                  -33.210       1 -0.002850
2025-05-03 19:45:00   96281.94   96357.15   96281.95   96354.34    46.28005   96214.285   96213.610     96106.4250      96324.030     96193.31               0.675                  -57.110       1  0.014828
2025-05-06 02:15:00   94214.00   94240.87   94059.99   94113.93   128.14534   94493.490   94537.505     94443.2900      94256.835     94375.90             -44.015                   32.565      -1 -0.023252
2025-05-07 08:30:00   96881.03   97053.91   96908.00   97020.00    94.39219   96748.315   96639.115     96682.1275      95595.990     96862.87             109.200                  -21.815       1 -0.030878
2025-05-09 06:15:00  102938.94  103224.43  102938.94  103131.46   264.98623  102847.870  102817.465    102678.0025     101632.305    102899.99              30.405                 -120.555       1  0.062992
2025-05-09 16:00:00  102873.01  102928.00  102528.02  102821.64   290.05279  103120.955  103136.830    103380.0250     103224.840    102949.71             -15.875                   24.495      -1 -0.003004
2025-05-09 23:15:00  102859.92  102968.26  102847.84  102934.19    91.58707  102911.635  102912.605    102979.6900     103375.155    103361.00              -0.970                   73.900      -1 -0.001095
2025-05-11 18:45:00  104488.58  104832.82  104488.58  104528.19   274.23095  104323.225  104309.915    104329.0325     104158.535    104280.01              13.310                 -101.025       1 -0.015486
2025-05-12 01:00:00  104526.32  105086.42  104551.28  104748.00  1076.07642  104430.510  104331.825    104264.6625     104116.535    104727.97              98.685                  -98.670       1  0.002103
2025-05-12 03:15:00  103858.44  104047.62  103825.40  103868.04   139.12615  104248.960  104331.825    104419.8600     104136.730    104459.34             -82.865                   68.230      -1 -0.008401
2025-05-12 07:00:00  104384.81  105819.45  104384.81  105600.00  2733.62710  104794.125  104766.570    104154.7475     104232.615    103801.89              27.555                 -309.865       1 -0.016675
2025-05-14 07:15:00  103588.00  103631.09  103391.37  103489.64   195.86309  103681.185  103737.040    104216.7775     103932.895    103970.87             -55.855                   44.550      -1 -0.019984
2025-05-15 14:45:00  101582.58  101987.65  101452.03  101987.65   381.23634  102121.880  102145.425    102336.5675     102796.710    103037.44             -23.545                   58.175      -1  0.014513
2025-05-18 22:45:00  105186.32  105979.99  105206.60  105928.10   633.21913  104975.455  104688.000    104904.4300     104410.160    102725.00             287.455                  -35.730       1 -0.038637
2025-05-19 12:30:00  102500.00  102636.80  102156.12  102393.55   433.80681  102614.835  102769.765    104072.4175     104904.575    104877.71            -154.930                    1.495      -1 -0.033367
2025-05-22 16:15:00  111510.61  111782.61  111261.00  111254.59   245.71409  111177.375  111142.525    110908.0700     109929.800    111020.93              34.850                  -13.505       1 -0.086539
2025-05-22 21:15:00  110927.20  111108.89  110765.30  110804.88   121.08161  111342.650  111372.650    111030.0125     110894.550    111100.01             -30.000                  105.720      -1 -0.004042
2025-05-23 00:15:00  111725.01  111783.38  111487.70  111478.26   169.66773  111393.130  111358.820    111390.8100     111137.525    110526.01              34.310                  -43.140       1 -0.006077
2025-05-23 04:15:00  110962.14  111046.06  110730.96  110815.72   228.51451  111174.945  111265.480    111234.7700     111137.525    111061.24             -90.535                   23.680      -1 -0.005943
2025-05-24 18:00:00  108916.01  109076.20  108920.03  109035.50    37.34448  108954.855  108948.190    108685.3025     108153.020    107502.44               6.665                  -59.885       1  0.016065
2025-05-25 16:00:00  106924.22  107056.00  106869.83  106901.74   577.30864  107218.840  107263.670    107372.9700     107849.090    108630.35             -44.830                   20.985      -1 -0.019569
2025-05-27 01:00:00  109107.11  109136.37  108900.00  108723.26   418.60250  109283.000  109384.460    109492.1550     109674.400    109495.23            -101.460                    8.535      -1 -0.017039
2025-05-27 16:45:00  110395.82  110499.64  110101.70  110217.39   176.71147  109818.005  109746.130    109450.4000     108778.990    108919.25              71.875                 -121.000       1 -0.013743
2025-05-29 07:00:00  107891.02  107993.58  107752.55  107993.57    88.67857  107753.055  107735.250    107512.7350     107929.450    107592.58              17.805                 -269.570       1 -0.020177
2025-05-30 11:45:00  105786.20  105963.27  105757.29  105880.51   156.47407  105513.710  105459.570    105748.7250     105858.035    104723.47              54.140                 -165.685       1 -0.019567
2025-05-31 10:00:00  103516.22  103598.75  103356.95  103476.01   169.82903  103583.230  103634.025    103760.9875     104461.975    104457.62             -50.795                   45.350      -1 -0.022710
2025-05-31 20:45:00  104715.94  104807.94  104715.94  104781.83    48.99706  104598.100  104573.075    103996.4125     103781.090    104137.32              25.025                   -3.945       1 -0.012620
2025-06-01 08:15:00  104262.47  104333.34  104240.00  104291.42    70.27044  104289.560  104327.260    104398.1275     104445.695    104599.70             -37.700                   38.595      -1 -0.004680
2025-06-03 19:15:00  106088.45  106400.00  106088.46  106351.96    83.50052  106001.890  105923.200    105240.1475     105700.005    105592.90              78.690                  -49.880       1 -0.019758
2025-06-04 20:15:00  104679.66  104756.62  104436.89  104681.96   218.10684  104850.730  104890.470    105194.7400     105372.390    104989.48             -39.740                  144.795      -1 -0.015703
2025-06-05 05:45:00  104660.37  104740.01  104591.64  104649.23   291.44569  104908.890  104916.240    104892.7150     105029.490    105408.74              -7.350                   44.805      -1  0.000313
2025-06-10 11:15:00  109439.18  109777.00  109439.18  109745.28   342.40294  109451.285  109417.860    109726.4600     109083.040    108711.37              33.425                  -78.395       1 -0.048696
2025-06-10 19:15:00  109467.77  110171.22  109472.77  110016.38   429.54384  109390.615  109273.755    109497.1275     109685.270    109605.53             116.860                  -64.990       1  0.002470
2025-06-13 20:30:00  105198.56  105508.34  105205.87  105505.03    78.60219  105088.535  105069.005    104908.1050     104170.350    105280.00              19.530                  -16.190       1 -0.041006
2025-06-13 21:45:00  105622.49  105788.79  105542.16  105612.59    66.05589  105419.950  105324.865    104952.2400     104439.295    105339.97              95.085                  -19.780       1  0.001019
2025-06-14 15:30:00  104862.60  104902.12  104658.83  104740.26   169.05610  104874.595  104895.040    105054.1025     105533.960    105454.16             -20.445                    0.460      -1 -0.008260
2025-06-15 19:30:00  105486.00  105516.45  105082.98  105149.99   147.70351  105430.035  105460.610    105216.6775     105500.250    105920.00             -30.575                   80.775      -1 -0.003912
2025-06-18 17:00:00  104331.87  104426.93  104042.98  104264.73   202.73042  104508.385  104594.820    104879.4525     104889.290    104649.09             -86.435                   53.815      -1  0.008419
2025-06-19 04:30:00  104836.19  104943.44  104812.75  104935.54    47.58637  104904.195  104869.190    104398.8300     104474.610    104843.15              35.005                  -47.220       1 -0.006434
2025-06-19 20:30:00  104331.00  104400.00  104168.00  104150.71    41.77266  104351.540  104380.275    104633.6550     104746.010    104569.30             -28.735                    7.535      -1 -0.007479
2025-06-19 22:30:00  104508.15  104750.00  104508.16  104685.53    55.91206  104450.000  104380.275    104480.0050     104649.005    104360.00              69.725                   -5.775       1 -0.005135
2025-06-20 04:30:00  104477.86  104500.41  104333.44  104345.74    78.49639  104516.720  104615.875    104377.3875     104509.675    105939.17             -99.155                    2.940      -1 -0.003246
2025-06-21 00:00:00  103250.01  103297.99  103172.01  103145.03    74.44757  103268.425  103297.435    103906.7625     104475.960    103520.00             -29.010                  214.790      -1  0.011507
2025-06-22 12:30:00  102646.58  102680.00  102593.44  102659.89    81.94384  102628.215  102545.995    102401.3375     102285.600     99186.24              82.220                  -17.490       1  0.004703
2025-06-23 16:15:00  100994.93  101075.03  100337.00  100272.18   735.87374  101340.500  101475.045    101658.5325     100618.500    105538.19            -134.545                  142.855      -1 -0.023258
2025-06-26 02:45:00  107669.69  108039.05  107566.57  107920.47   228.93846  107573.590  107566.675    107508.8675     107240.285    107458.51               6.915                  -18.085       1 -0.076275
2025-06-26 08:15:00  108078.87  108174.86  107800.01  107854.26   160.61322  107919.675  107896.230    107525.6075     107467.640    107436.60              23.445                  -71.415       1 -0.000614

In [6]:
print(data.columns)

Index(['open', 'high', 'low', 'close', 'volume', 'tenkan_sen', 'kijun_sen', 'senkou_span_a', 'senkou_span_b', 'chikou_span', 'tenkan_minus_kijun', 'prev_tenkan_minus_kijun', 'signal', 'pnl'], dtype='object')

In [10]:
import plotly.graph_objects as go
import plotly.offline as pyo
fig= go.Figure()

In [13]:
# plot ohlc candles for btcusdt

fig.add_trace(go.Candlestick(
    x= data.index,
    open= data["open"],
    high= data["high"],
    low= data["low"],
    close= data["close"],
    name= "BTCUSDT OHLC"))

#Ichimoku Lines
fig.add_trace(go.Scatter(x=data.index, y=data['tenkan_sen'], line=dict(color='blue'), name='Tenkan Sen'))
fig.add_trace(go.Scatter(x=data.index, y=data['kijun_sen'], line=dict(color='purple'), name='Kijun Sen'))
fig.add_trace(go.Scatter(x=data.index, y=data['senkou_span_a'], line=dict(color='green'), name='Senkou Span A', fill=None))
fig.add_trace(go.Scatter(x=data.index, y=data['senkou_span_b'], line=dict(color='red'), name='Senkou Span B', fill='tonexty', fillcolor='rgba(50,200,50,0.2)'))
fig.add_trace(go.Scatter(x=data.index, y=data['chikou_span'], line=dict(color='orange'), name='Chikou Span'))

# Mark Buy Signals
buy_signals = data[data['signal'] == 1]
fig.add_trace(go.Scatter(mode='markers', x=buy_signals.index, y=buy_signals['close'],
                         marker=dict(color='green', size=10, symbol='triangle-up'),
                         name='Buy Signal'))

# Mark Sell Signals
sell_signals = data[data['signal'] == -1]
fig.add_trace(go.Scatter(mode='markers', x=sell_signals.index, y=sell_signals['close'],
                         marker=dict(color='red', size=10, symbol='triangle-down'),
                         name='Sell Signal'))


# Update Layout
fig.update_layout(
    title="Ichimoku Trading Strategy Visualization",
    xaxis_title="Date",
    yaxis_title="Price",
    legend_title="Legend",
    width=1200,
    height=600
)

pyo.plot(fig, filename= "ichimoku.html")

'ichimoku.html'