
## Collecting Data from API

Opening conda prompt:

1. cd /d D:\crypto_trading

2. conda activate cryptotrading

3. jupyter notebook

https://developers.binance.com/docs/binance-spot-api-docs

https://www.bitmex.com/app/apiOverview

In [21]:
# import necessary files
import logging
from exchanges.binance import BinanceClient
from exchanges.coinbase import CoinbaseClient
from database import Hdf5Client
from utils.time_convertor import *
import pandas as pd
import numpy as np
import time

#strategies
import strategies.obv
import strategies.ichimoku as ic

In [22]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)
pd.set_option("display.width", 5000)
pd.set_option('display.expand_frame_repr', False)  # prevent wrapping of DataFrame

In [23]:
h5_db= Hdf5Client("Binance")
data= h5_db.get_data("BTCUSDT", from_time= 0, to_time= int(time.time() * 1000))

In [24]:
#import and format the data
data= resample_timeframe(data, "1h")
data

                          open       high        low      close        volume
timestamp
2025-03-26 06:00:00   87491.02   87923.92   87491.03   87909.07    411.588490
2025-03-26 07:00:00   87881.90   88275.00   87774.36   88140.45   1053.471940
2025-03-26 08:00:00   88132.30   88200.00   87888.00   87959.73    525.113310
2025-03-26 09:00:00   87959.73   88056.61   87853.99   87939.99    393.097500
2025-03-26 10:00:00   87939.99   88259.81   87940.00   88208.47    556.205410
2025-03-26 11:00:00   88208.46   88242.00   87960.00   87954.96    940.317970
2025-03-26 12:00:00   87952.11   88000.00   87613.88   87813.17    825.399060
2025-03-26 13:00:00   87762.00   87920.08   86856.83   86841.31   1682.405840
2025-03-26 14:00:00   86738.40   87294.05   86473.03   86773.14   1940.957520
2025-03-26 15:00:00   86738.23   87018.87   86594.00   86752.52   1188.338680
2025-03-26 16:00:00   86605.12   87058.40   86447.81   86513.99    751.205080
2025-03-26 17:00:00   86480.01   86829.88   86491.06   86569.99    568.002280
2025-03-26 18:00:00   86565.66   86750.01   86228.18   86198.53    562.824370
2025-03-26 19:00:00   86198.15   86800.77   85875.66   86567.19   1124.928160
2025-03-26 20:00:00   86520.10   87404.34   86567.18   87280.00    896.058090
2025-03-26 21:00:00   87277.23   87302.00   86791.05   87109.65    541.366010
2025-03-26 22:00:00   86963.48   87147.92   86765.19   86829.48    347.876030
2025-03-26 23:00:00   86826.00   86952.20   86563.69   86909.17    333.754320
2025-03-27 00:00:00   86909.17   87308.00   86803.24   87285.29    439.268330
2025-03-27 01:00:00   87283.75   87519.38   87184.96   87378.87    484.205780
2025-03-27 02:00:00   87338.79   87756.39   87353.00   87575.39    474.682540
2025-03-27 03:00:00   87569.17   87675.00   87436.81   87670.18    493.007570
2025-03-27 04:00:00   87653.88   87691.34   87431.64   87521.61    389.929170
2025-03-27 05:00:00   87473.31   87521.60   87264.38   87314.72    498.024320
2025-03-27 06:00:00   87288.31   87547.60   87280.01   87352.68    421.131390
2025-03-27 07:00:00   87352.67   87439.30   87254.72   87399.99    466.033020
2025-03-27 08:00:00   87370.21   87597.60   87269.71   87434.82    539.098200
2025-03-27 09:00:00   87409.53   87537.74   87406.18   87415.56    453.074670
2025-03-27 10:00:00   87400.33   87597.60   87145.72   87195.59    529.031390
2025-03-27 11:00:00   87150.55   87316.29   86815.98   86943.52    674.570690
2025-03-27 12:00:00   86830.71   87110.10   86738.52   86761.05    665.706090
2025-03-27 13:00:00   86721.70   86861.71   85860.04   86383.83   2610.927820
2025-03-27 14:00:00   86356.92   87321.56   86189.19   87297.33   2709.469750
2025-03-27 15:00:00   87252.00   87575.00   86781.99   86974.07   1554.663610
2025-03-27 16:00:00   86928.28   87271.43   86831.58   86835.24    671.699860
2025-03-27 17:00:00   86835.24   87150.95   86814.81   86913.05    596.491920
2025-03-27 18:00:00   86898.00   87420.00   86910.01   87206.52    473.096320
2025-03-27 19:00:00   87198.11   87429.21   87086.17   87060.41    473.800580
2025-03-27 20:00:00   87054.00   87346.07   86947.45   87307.57    454.462990
2025-03-27 21:00:00   87307.56   87728.27   87247.90   87568.68    488.703620
2025-03-27 22:00:00   87559.80   87600.00   87325.41   87350.71    263.446750
2025-03-27 23:00:00   87336.96   87361.07   87128.01   87232.01    273.512590
2025-03-28 00:00:00   87230.20   87402.08   86970.00   87354.01    438.181730
2025-03-28 01:00:00   87323.23   87515.67   87129.70   87230.29    516.426960
2025-03-28 02:00:00   87230.30   87327.98   86961.11   86987.77    388.731320
2025-03-28 03:00:00   86964.85   87018.36   86790.83   86787.16    568.380440
2025-03-28 04:00:00   86787.16   86832.64   85985.53   86305.38   1475.680930
2025-03-28 05:00:00   86160.37   86305.38   85832.66   86059.02   1025.354920
2025-03-28 06:00:00   85978.56   86250.00   85690.12   85719.27   1011.001240
2025-03-28 07:00:00   85661.46   85888.60   85182.76   85212.99   2159.059190
2025-03-28 08:00:00   85161.70   85441.25   85058.82   85213.87   1389.578700
2025-03-28 09:00:00   85185.04   85417.47   85034.93   85148.00   1298.566220
2025-03-28 10:00:00   85111.64   85250.79   84896.00   84941.49    988.614560
2025-03-28 11:00:00   84921.48   85255.26   84817.61   85255.26   1274.000290
2025-03-28 12:00:00   85235.48   85609.74   84893.46   85028.27   1145.415190
2025-03-28 13:00:00   85016.90   85575.68   84944.67   84994.00   1317.090600
2025-03-28 14:00:00   84896.35   85120.19   84154.00   84172.01   3331.052980
2025-03-28 15:00:00   84117.36   84530.45   84019.55   84051.16   2589.079550
2025-03-28 16:00:00   84049.42   84217.61   83765.27   83794.73   1152.231310
2025-03-28 17:00:00   83760.00   84010.41   83589.69   84008.45   1114.865900
2025-03-28 18:00:00   83971.69   84169.52   83730.44   83880.00    755.869230
2025-03-28 19:00:00   83866.63   83893.48   83648.42   83790.73    834.896680
2025-03-28 20:00:00   83764.48   84160.38   83747.59   83794.41   1271.034330
2025-03-28 21:00:00   83794.41   84110.36   83710.00   84052.29    295.776850
2025-03-28 22:00:00   84052.29   84480.36   84052.29   84480.35    382.783310
2025-03-28 23:00:00   84462.76   84538.69   84207.55   84424.38    459.059260
2025-03-29 00:00:00   84388.00   84624.73   84364.79   84396.89    414.883070
2025-03-29 01:00:00   84375.29   84502.42   84223.83   84281.90    283.363850
2025-03-29 02:00:00   84281.91   84423.53   83855.59   83851.40    407.568270
2025-03-29 03:00:00   83848.01   84254.72   83750.07   84166.30    420.198600
2025-03-29 04:00:00   84154.34   84258.45   83980.29   84072.96    287.249560
2025-03-29 05:00:00   84072.96   84093.99   83858.23   84012.64    235.853660
2025-03-29 06:00:00   83991.59   84012.65   83672.74   83787.28    335.982130
2025-03-29 07:00:00   83770.30   83892.00   83666.67   83731.82    244.436290
2025-03-29 08:00:00   83718.00   83944.36   83666.65   83934.95    340.177470
2025-03-29 09:00:00   83914.05   83947.42   83410.01   83544.80    720.141630
2025-03-29 10:00:00   83524.46   83559.23   82850.57   82927.81    735.212770
2025-03-29 11:00:00   82850.90   83108.08   82022.91   82293.56   1843.369300
2025-03-29 12:00:00   82240.00   82527.70   82159.50   82462.70    634.076290
2025-03-29 13:00:00   82454.44   82863.49   82462.69   82851.95    578.260670
2025-03-29 14:00:00   82816.71   82882.01   82483.15   82504.01    452.613800
2025-03-29 15:00:00   82500.00   82617.01   82386.51   82414.23    295.797230
2025-03-29 16:00:00   82414.22   82683.78   82186.95   82198.43    538.750640
2025-03-29 17:00:00   82171.94   82625.05   81665.22   82332.63   1231.201970
2025-03-29 18:00:00   82268.70   82673.00   82234.38   82343.64    368.885730
2025-03-29 19:00:00   82305.92   82758.41   82218.88   82758.40    370.868950
2025-03-29 20:00:00   82652.23   82787.29   82447.83   82511.17    376.359690
2025-03-29 21:00:00   82489.10   82685.45   82380.12   82518.74    212.791050
2025-03-29 22:00:00   82439.61   82522.00   82270.01   82389.75    188.292290
2025-03-29 23:00:00   82385.76   82679.52   82348.00   82648.54    180.063730
2025-03-30 00:00:00   82595.23   82888.93   82500.00   82799.73    310.375140
2025-03-30 01:00:00   82762.71   83075.48   82799.38   82941.13    445.847840
2025-03-30 02:00:00   82925.67   83372.81   82941.14   83330.00    417.672010
2025-03-30 03:00:00   83317.65   83503.53   83071.39   83088.81    431.746130
2025-03-30 04:00:00   83088.81   83314.42   83078.94   83109.81    213.200240
2025-03-30 05:00:00   83109.80   83230.00   82924.24   82958.30    272.841160
2025-03-30 06:00:00   82958.29   83306.26   82868.96   83178.14    402.671070
2025-03-30 07:00:00   83178.14   83321.16   83073.05   83076.59    349.726830
2025-03-30 08:00:00   83076.58   83406.14   83076.58   83378.09    354.718990
2025-03-30 09:00:00   83362.13   83517.78   83268.47   83502.32    224.075360
2025-03-30 10:00:00   83486.96   83534.64   83064.17   83120.87    292.389350
2025-03-30 11:00:00   83120.86   83360.31   82989.27   83111.76    334.935950
2025-03-30 12:00:00   83109.65   83268.05   82989.26   83072.76    356.536890
2025-03-30 13:00:00   83068.13   83155.17   82662.01   82678.42   1050.992850
2025-03-30 14:00:00   82678.42   83043.59   82630.02   82803.28    466.767080
2025-03-30 15:00:00   82803.28   83067.90   82732.02   82729.57    280.141080
2025-03-30 16:00:00   82710.48   82816.00   82201.89   82284.01    603.144990
2025-03-30 17:00:00   82250.00   82577.99   82059.70   82415.53    398.110750
2025-03-30 18:00:00   82415.53   82799.99   82415.54   82729.65    321.945930
2025-03-30 19:00:00   82707.83   82908.11   82550.05   82548.81    258.331760
2025-03-30 20:00:00   82544.80   82650.95   82400.01   82554.73    201.030050
2025-03-30 21:00:00   82554.73   82703.94   82069.41   82237.68    258.821660
2025-03-30 22:00:00   82086.00   82757.70   81577.86   82438.00    997.389990
2025-03-30 23:00:00   82391.98   82442.94   81964.95   82389.99    621.081980
2025-03-31 00:00:00   82368.48   82444.89   81333.98   81646.89   1156.904700
2025-03-31 01:00:00   81534.78   82272.72   81543.25   81953.03    778.608830
2025-03-31 02:00:00   81900.00   82179.25   81644.00   81922.30    652.558370
2025-03-31 03:00:00   81906.00   82030.00   81490.01   81530.00    549.387110
2025-03-31 04:00:00   81529.09   81879.16   81417.47   81846.01    489.047800
2025-03-31 05:00:00   81830.00   82305.57   81846.00   82166.99    520.567410
2025-03-31 06:00:00   82166.98   82267.66   81938.55   82052.83    641.586310
2025-03-31 07:00:00   82046.00   82303.58   81765.75   81933.51    776.648170
2025-03-31 08:00:00   81908.19   82263.74   81914.38   81899.15    762.807570
2025-03-31 09:00:00   81889.34   81960.56   81371.68   81455.58    965.895570
2025-03-31 10:00:00   81451.90   82215.91   81325.68   82174.16    713.595130
2025-03-31 11:00:00   82174.16   82272.00   81893.04   82205.51    980.634120
2025-03-31 12:00:00   82185.63   83169.82   81939.36   82768.74   1527.489470
2025-03-31 13:00:00   82706.58   82866.02   81761.36   82507.99   2027.952580
2025-03-31 14:00:00   82507.49   83746.23   82507.99   83499.18   2160.575470
2025-03-31 15:00:00   83499.18   83943.08   83411.39   83418.78   1241.909230
2025-03-31 16:00:00   83418.78   83694.29   83273.18   83288.89    658.286560
2025-03-31 17:00:00   83261.76   83545.55   82586.00   82680.34    667.392630
2025-03-31 18:00:00   82676.00   83566.00   82680.35   83291.42    810.730870
2025-03-31 19:00:00   83282.00   83443.38   82412.81   82462.27    798.209250
2025-03-31 20:00:00   82405.02   82846.20   82376.82   82431.32    701.198120
2025-03-31 21:00:00   82422.00   82752.18   82431.32   82563.99    342.528650
2025-03-31 22:00:00   82553.00   82571.98   82280.15   82409.99    260.876470
2025-03-31 23:00:00   82388.21   82886.80   82295.86   82550.01    383.748460
2025-04-01 00:00:00   82490.76   82837.38   82432.74   82651.10    526.959220
2025-04-01 01:00:00   82605.34   82741.80   82470.01   82704.20    440.090930
2025-04-01 02:00:00   82685.24   83120.00   82649.34   83100.00    522.782460
2025-04-01 03:00:00   83065.23   83256.80   82926.10   82962.84    526.153630
2025-04-01 04:00:00   82914.39   83235.96   82887.01   83060.00    425.378740
2025-04-01 05:00:00   83031.57   83329.99   82994.08   83006.67    348.443640
2025-04-01 06:00:00   83000.01   83494.25   82900.01   83454.76    425.660160
2025-04-01 07:00:00   83454.75   83597.07   83387.07   83445.50    622.585510
2025-04-01 08:00:00   83410.00   84207.55   83445.50   84121.94   1217.292790
2025-04-01 09:00:00   84121.93   84395.46   84121.94   84362.00   1018.971860
2025-04-01 10:00:00   84311.68   84504.74   84169.81   84175.99    914.761180
2025-04-01 11:00:00   84161.58   84203.00   83846.38   83930.30    854.543510
2025-04-01 12:00:00   83924.52   84154.22   83628.16   83615.26    734.992560
2025-04-01 13:00:00   83596.00   83912.62   83430.69   83618.23   1152.681040
2025-04-01 14:00:00   83480.00   84350.00   82637.99   84195.92   2522.860470
2025-04-01 15:00:00   84182.89   85499.55   84195.92   85280.87   2484.930750
2025-04-01 16:00:00   85275.21   85493.00   84815.32   85119.99   1208.484920
2025-04-01 17:00:00   85028.12   85333.33   84904.25   85117.85    775.262400
2025-04-01 18:00:00   85038.01   85183.46   84726.64   85126.68    742.895530
2025-04-01 19:00:00   85095.97   85184.89   84836.97   84972.01    897.453260
2025-04-01 20:00:00   84920.48   85350.00   84782.36   85231.28    528.396380
2025-04-01 21:00:00   85231.28   85476.86   85138.01   85223.84    325.841410
2025-04-01 22:00:00   85219.90   85483.38   85114.88   85099.99    477.113020
2025-04-01 23:00:00   85084.80   85579.46   84991.80   85158.34    495.861600
2025-04-02 00:00:00   85158.35   85255.95   84940.78   84964.49    472.950930
2025-04-02 01:00:00   84956.31   85213.12   84870.85   85147.30    597.768960
2025-04-02 02:00:00   85101.08   85174.89   84665.22   84714.36    850.774360
2025-04-02 03:00:00   84706.21   84904.00   84532.43   84550.00    475.509660
2025-04-02 04:00:00   84517.00   84726.42   84475.46   84607.00    444.662260
2025-04-02 05:00:00   84567.60   84607.00   84117.15   84100.00    550.684820
2025-04-02 06:00:00   84046.00   84371.59   83931.29   84125.99    646.497800
2025-04-02 07:00:00   84120.00   84462.16   84039.79   84426.33    642.707380
2025-04-02 08:00:00   84351.77   84762.72   84262.74   84677.04    535.256650
2025-04-02 09:00:00   84635.60   85450.00   84677.04   85019.62    910.863510
2025-04-02 10:00:00   85015.50   85299.45   84851.98   84867.92    592.830320
2025-04-02 11:00:00   84746.18   84985.77   84558.69   84566.91    463.522710
2025-04-02 12:00:00   84554.43   85054.78   84487.90   85049.99    742.570820
2025-04-02 13:00:00   84983.68   86136.36   84531.34   85215.82   2792.280520
2025-04-02 14:00:00   85181.52   86000.00   85215.79   85877.75   2062.013420
2025-04-02 15:00:00   85811.20   87333.00   85877.74   86757.67   5585.702140
2025-04-02 16:00:00   86697.78   87221.99   86603.77   87065.18   2549.141960
2025-04-02 17:00:00   87039.92   87333.00   86391.97   86615.33   2025.448110
2025-04-02 18:00:00   86581.55   86751.79   86236.46   86286.02    685.232900
2025-04-02 19:00:00   86286.03   87000.00   86206.56   86900.02    812.773360
2025-04-02 20:00:00   86774.82   88500.00   85299.48   85659.99   7832.634990
2025-04-02 21:00:00   85615.64   85743.22   84260.00   84855.99   1793.310350
2025-04-02 22:00:00   84582.79   84855.98   82737.64   82821.59   3036.674270
2025-04-02 23:00:00   82560.59   82845.42   82384.65   82516.29   2829.644800
2025-04-03 00:00:00   82436.40   83424.72   82212.01   83227.55   1848.780370
2025-04-03 01:00:00   83190.00   83998.02   83138.90   83761.62   1735.380820
2025-04-03 02:00:00   83750.94   83894.91   83284.44   83768.01   1422.271460
2025-04-03 03:00:00   83743.89   83792.58   83349.66   83483.97    638.138130
2025-04-03 04:00:00   83454.94   83735.85   83300.00   83558.80    630.552660
2025-04-03 05:00:00   83556.93   83709.48   83348.26   83343.75    457.594970
2025-04-03 06:00:00   83300.00   83415.47   83008.74   83058.65    568.508340
2025-04-03 07:00:00   83036.47   83498.10   83025.01   83456.75    774.524070
2025-04-03 08:00:00   83456.74   83788.23   83456.76   83679.99    821.936770
2025-04-03 09:00:00   83677.10   83766.69   83449.92   83483.05    539.185410
2025-04-03 10:00:00   83469.49   83749.99   83170.66   83220.01   1239.616160
2025-04-03 11:00:00   83129.71   83347.39   83047.34   83096.01    608.061620
2025-04-03 12:00:00   83047.00   83147.95   81916.01   81949.06   1872.330470
2025-04-03 13:00:00   81890.00   82792.46   81802.41   82373.58   2339.513900
2025-04-03 14:00:00   82161.32   82403.50   81374.94   81532.00   2364.560000
2025-04-03 15:00:00   81479.17   82101.42   81316.82   82039.31   2246.654330
2025-04-03 16:00:00   82018.24   82448.21   81735.13   81830.56   1010.180980
2025-04-03 17:00:00   81816.12   82191.11   81645.71   81830.01    889.366720
2025-04-03 18:00:00   81830.00   82317.99   81550.85   82109.45    990.199650
2025-04-03 19:00:00   82081.24   82362.41   81869.40   82008.70   1247.726360
2025-04-03 20:00:00   81951.95   82421.49   81821.46   82363.99   1289.977490
2025-04-03 21:00:00   82347.51   82864.00   82333.87   82717.54    615.389650
2025-04-03 22:00:00   82622.80   82869.99   82616.42   82743.46    432.331760
2025-04-03 23:00:00   82743.45   83332.20   82533.16   83213.09    755.059260
2025-04-04 00:00:00   83178.85   83413.46   83000.02   83046.32   1239.490060
2025-04-04 01:00:00   83046.31   83358.50   82618.49   82695.91    989.866530
2025-04-04 02:00:00   82695.90   83186.96   82695.90   82910.86    396.197220
2025-04-04 03:00:00   82908.28   83069.96   82698.12   82818.52    416.145030
2025-04-04 04:00:00   82816.29   82920.19   82615.36   82720.32    664.543690
2025-04-04 05:00:00   82720.31   83212.17   82650.44   83200.00    628.674900
2025-04-04 06:00:00   83199.99   83264.16   83048.99   83054.72    400.851920
2025-04-04 07:00:00   83054.72   84000.00   83054.73   83992.85   1397.795340
2025-04-04 08:00:00   83992.85   84650.00   83992.85   84415.99   1616.222360
2025-04-04 09:00:00   84416.00   84720.00   84159.99   84571.38    882.781020
2025-04-04 10:00:00   84565.91   84690.00   82442.07   82567.03   4808.433620
2025-04-04 11:00:00   82565.20   82768.09   81743.16   82680.45   2375.098530
2025-04-04 12:00:00   82495.01   83200.00   82248.32   82879.99   2300.224390
2025-04-04 13:00:00   82872.29   83507.19   82144.95   83335.99   2211.631200
2025-04-04 14:00:00   83296.79   83510.00   81877.08   82573.98   2330.639910
2025-04-04 15:00:00   82488.88   83716.00   82573.98   82860.00   3250.109090
2025-04-04 16:00:00   82860.00   83555.00   82738.00   83392.70   1380.469680
2025-04-04 17:00:00   83376.82   84620.01   83032.00   84460.00   2047.817960
2025-04-04 18:00:00   84459.99   84584.91   83775.18   83989.87   1110.660340
2025-04-04 19:00:00   83950.01   84460.00   83788.01   84009.99    835.236800
2025-04-04 20:00:00   83984.52   84282.00   83516.30   84164.02    600.667970
2025-04-04 21:00:00   84119.66   84450.00   83941.43   84185.80    427.973480
2025-04-04 22:00:00   84185.80   84271.28   84018.86   84056.74    252.048790
2025-04-04 23:00:00   84056.74   84100.00   83650.12   83889.87    351.959930
2025-04-05 00:00:00   83827.93   83889.88   83473.56   83787.60    475.672600
2025-04-05 01:00:00   83787.59   84266.00   83787.60   83979.87    382.389280
2025-04-05 02:00:00   83979.88   84094.57   83834.09   83976.61    371.161590
2025-04-05 03:00:00   83957.88   83976.61   83638.69   83624.01    476.529100
2025-04-05 04:00:00   83621.73   83868.00   83620.33   83677.75    332.912190
2025-04-05 05:00:00   83677.74   83863.36   83634.31   83688.67    231.145480
2025-04-05 06:00:00   83685.29   83724.39   83341.99   83477.30    394.810900
2025-04-05 07:00:00   83458.38   83558.65   83382.02   83525.34    322.081660
2025-04-05 08:00:00   83516.06   83648.63   83375.57   83519.96    287.897550
2025-04-05 09:00:00   83519.76   83865.10   83519.97   83843.29    329.664190
2025-04-05 10:00:00   83843.28   83894.70   83586.56   83641.51    209.986820
2025-04-05 11:00:00   83641.50   83700.52   83443.48   83452.69    405.741720
2025-04-05 12:00:00   83429.19   83550.68   83157.33   83281.41    447.965670
2025-04-05 13:00:00   83269.60   83335.56   82542.61   82755.29    932.445730
2025-04-05 14:00:00   82726.00   83026.00   82708.69   82914.67    391.756120
2025-04-05 15:00:00   82904.05   82914.67   82394.00   82618.26    804.805110
2025-04-05 16:00:00   82611.80   82827.37   82609.55   82739.96    246.003240
2025-04-05 17:00:00   82729.32   82953.20   82681.65   82869.53    200.383810
2025-04-05 18:00:00   82854.80   83109.46   82869.53   83036.13    308.689730
2025-04-05 19:00:00   83036.13   83146.00   82781.96   82860.00    219.106660
2025-04-05 20:00:00   82859.99   83113.67   82833.00   83075.47    404.280100

## Testing out strategies:

##### Ichimoku:

In [25]:
ichimoku_df= data.copy()

In [26]:
#tenkan
ichimoku_df["rolling_min_tenkan"]= ichimoku_df['low'].rolling(window=9).min()
ichimoku_df["rolling_max_tenkan"]= ichimoku_df['high'].rolling(window=9).max()
ichimoku_df['tenkan_sen'] = (ichimoku_df["rolling_min_tenkan"]+ ichimoku_df["rolling_max_tenkan"]) / 2

ichimoku_df.drop(columns=["rolling_min_tenkan", "rolling_max_tenkan"], axis=1, inplace=True)

# Base Line: Kijun Sen
ichimoku_df["rolling_min_kijun"]= ichimoku_df['low'].rolling(window=26).min()
ichimoku_df["rolling_max_kijun"]= ichimoku_df['high'].rolling(window=26).max()
ichimoku_df['kijun_sen'] = (ichimoku_df["rolling_min_kijun"]+ichimoku_df["rolling_max_kijun"]) / 2

ichimoku_df.drop(columns=["rolling_min_kijun", "rolling_max_kijun"], axis=1, inplace=True)   

# Leading Span A: Senkou Span A
ichimoku_df['senkou_span_a'] = ((ichimoku_df['tenkan_sen'] + ichimoku_df['kijun_sen']) / 2).shift(26)

# Leading Span B: Senkou Span B
ichimoku_df['rolling_senkou'] = ((ichimoku_df['high'].rolling(window=26*2).max()) + (ichimoku_df['low'].rolling(window=26*2)).min()) / 2
ichimoku_df['senkou_span_b'] = ichimoku_df['rolling_senkou'].shift(26)

ichimoku_df.drop(columns=["rolling_senkou"], axis=1, inplace=True)

# Lagging Span: Chikou Span
# Chikou Span is the closing price shifted back by 26 periods
ichimoku_df['chikou_span'] = ichimoku_df['close'].shift(-1 * 26)

ichimoku_df.dropna(inplace=True)

   

#Signal
ichimoku_df["tenkan_minus_kijun"]= ichimoku_df["tenkan_sen"] - ichimoku_df["kijun_sen"]
ichimoku_df["prev_tenkan_minus_kijun"]= ichimoku_df["tenkan_minus_kijun"].shift(1)
ichimoku_df["prev_senkou_span_a"]= ichimoku_df["senkou_span_a"].shift(1)
ichimoku_df["prev_senkou_span_b"]= ichimoku_df["senkou_span_b"].shift(1)
ichimoku_df["signal"]= np.where(
        (ichimoku_df["tenkan_minus_kijun"] > 0)  #tenkan sen and kijun sen crossover
        & (ichimoku_df["prev_tenkan_minus_kijun"] < 0) 
        & (ichimoku_df["close"]> ichimoku_df["senkou_span_a"]) # close price greater than senkou span A
        & (ichimoku_df["close"] > ichimoku_df["senkou_span_b"]) # close price greater than senkou span B
        & (ichimoku_df["close"]> ichimoku_df["chikou_span"]) # close price greater than chikou span
        #& (ichimoku_df["senkou_span_a"] > ichimoku_df["senkou_span_b"]) # senkou span A greater than senkou span B
        #& (ichimoku_df["prev_senkou_span_a"] < ichimoku_df["prev_senkou_span_b"])
        , 1,  # bullish or long signal

        np.where(
        (ichimoku_df["tenkan_minus_kijun"] < 0) 
        & (ichimoku_df["prev_tenkan_minus_kijun"] > 0) 
        & (ichimoku_df["close"]< ichimoku_df["senkou_span_a"])
        & (ichimoku_df["close"]< ichimoku_df["senkou_span_b"])
        & (ichimoku_df["close"]< ichimoku_df["chikou_span"])
        #& (ichimoku_df["senkou_span_a"] < ichimoku_df["senkou_span_b"])
        #& (ichimoku_df["prev_senkou_span_a"] > ichimoku_df["prev_senkou_span_b"])
        , -1, 0) # bearish or short signal, otherwise no signal
)  

# Calculate PnL
# Dataframe only with 1 or -1 signals
signal_data= ichimoku_df[ichimoku_df["signal"] != 0].copy()
# Calculate the percentage change in close price and shift the signal by 1 to align with the previous signal
signal_data["pnl"]= signal_data["close"].pct_change() * signal_data["signal"].shift(1)

#Calculating Maximum Drawdown
signal_data["cum_pnl"]= signal_data["pnl"].cumsum()
signal_data["max_cum_pnl"]= signal_data["cum_pnl"].cummax()
signal_data["drawdown"]= signal_data["max_cum_pnl"] - signal_data["cum_pnl"]

#Calculating the maximum drwadown in percentage:
signal_data["cum_returns"]= (1 + signal_data["pnl"]).cumprod()
signal_data["max_cum_returns"]= signal_data["cum_returns"].cummax()
signal_data["drawdown_pct"]= (signal_data["cum_returns"] - signal_data["max_cum_returns"]) / signal_data["max_cum_returns"]
signal_data["drawdown_pct"]= signal_data["drawdown_pct"].fillna(0) * 100  # Convert to percentage

In [27]:
signal_data.head(30)

                          open       high        low      close      volume  tenkan_sen   kijun_sen  senkou_span_a  senkou_span_b  chikou_span  tenkan_minus_kijun  prev_tenkan_minus_kijun  prev_senkou_span_a  prev_senkou_span_b  signal       pnl   cum_pnl  max_cum_pnl  drawdown  cum_returns  max_cum_returns  drawdown_pct
timestamp
2025-03-30 19:00:00   82707.83   82908.11   82550.05   82548.81   258.33176   82710.005   82797.170     82975.6475      84696.745     82563.99             -87.165                  197.240          83154.4925           84875.590      -1       NaN       NaN          NaN       NaN          NaN              NaN      0.000000
2025-04-15 02:00:00   84983.73   85300.01   84728.76   85232.83   611.38477   84838.995   84808.360     84336.7875      84452.430     83587.99              30.635                  -22.815          84301.9200           84452.430       1 -0.032514 -0.032514    -0.032514  0.000000     0.967486         0.967486      0.000000
2025-04-17 02:00:00   84296.46   84337.99   84038.00   84272.86   254.74825   83980.370   84323.005     84489.7475      84777.575     84663.71            -342.635                   67.600          84771.0050           84777.575      -1 -0.011263 -0.043777    -0.032514  0.011263     0.956589         0.967486     -1.126291
2025-04-24 00:00:00   93679.95   93787.65   93253.61   93357.22   891.30897   93566.730   93320.755     91188.1925      89204.870     92992.33             245.975                 -238.060          90929.6800           89181.385       1 -0.107797 -0.151574    -0.032514  0.119060     0.853472         0.967486    -11.784579
2025-04-28 23:00:00   94809.52   95180.00   94809.52   95011.18   768.18162   94328.100   94227.140     94292.5675      94498.455     94527.73             100.960                  -29.040          94264.9025           94591.450       1  0.017716 -0.133858    -0.032514  0.101343     0.868592         0.967486    -10.221713
2025-04-29 22:00:00   94580.50   94735.65   94060.15   94163.67  1003.36560   94760.070   94760.840     94390.1200      94227.140     94405.47              -0.770                   73.345          94390.1200           94227.140      -1 -0.008920 -0.142778    -0.032514  0.110264     0.860844         0.967486    -11.022545
2025-04-30 13:00:00   94452.00   94649.50   93074.16   93032.58  2712.01725   94151.305   94267.075     94652.1025      94227.140     96854.30            -115.770                  192.950          94604.2375           94227.140      -1  0.012012 -0.130766    -0.032514  0.098252     0.871185         0.967486     -9.953752
2025-05-06 10:00:00   94197.56   94329.63   93881.77   93942.83   952.04682   94259.890   94406.335     94531.9700      95101.405     96966.08            -146.445                   75.495          94599.9700           95101.405      -1 -0.009784 -0.140550    -0.032514  0.108036     0.862661         0.967486    -10.834783
2025-05-11 11:00:00  104633.54  104777.00  104391.51  104652.01   611.74101  104061.035  104020.480    103367.9375     101550.950    104319.99              40.555                  -13.765         103425.2025          101549.695       1 -0.113997 -0.254547    -0.032514  0.222033     0.764320         0.967486    -20.999331
2025-05-25 02:00:00  107656.21  108000.00  107480.30  107928.80   339.41198  108185.840  108376.355    108802.3875     109390.005    109541.30            -190.515                   13.380         108812.5100          109390.005      -1  0.031311 -0.223236    -0.032514  0.190721     0.788252         0.967486    -18.525717
2025-05-27 11:00:00  109680.76  109783.53  109448.29  109585.49   450.26661  109085.865  109040.600    109079.9750     108446.220    108068.45              45.265                 -122.040         108959.6550          108446.220       1 -0.015350 -0.238585    -0.032514  0.206071     0.776152         0.967486    -19.776335
2025-06-02 23:00:00  105676.32  105931.44  105622.57  105857.99   540.70423  104945.525  104812.155    104685.9900     104298.810    105592.90             133.370                  -67.815         104544.3975          104196.475       1 -0.034015 -0.272600    -0.032514  0.240086     0.749752         0.967486    -22.505106
2025-06-11 00:00:00  110229.08  110274.40  109828.29  109825.54   496.67292  109505.005  109388.145    108351.4550     107765.585    108400.52             116.860                  -10.000         108315.4425          107765.585       1  0.037480 -0.235120    -0.032514  0.202606     0.777853         0.967486    -19.600602
2025-06-15 20:00:00  105280.61  105300.00  104613.03  104729.53   453.57123  105225.635  105234.045    105039.8175     105625.075    107700.01              -8.410                  145.075         105040.0725          105625.075      -1 -0.046401 -0.281521    -0.032514  0.249007     0.741760         0.967486    -23.331211
2025-06-18 19:00:00  103500.00  104437.70  103623.39  103808.41   839.17523  104474.610  104586.830    105604.1550     106178.295    104332.45            -112.220                    1.995         105720.8900          106253.290      -1  0.008795 -0.272726    -0.032514  0.240211     0.748283         0.967486    -22.656892
2025-06-20 07:00:00  104701.68  105825.66  104649.34  105811.74  1083.81217  105034.510  104885.740    104704.2975     105587.775    103843.37             148.770                  -12.075         104523.0050          105587.775       1 -0.019298 -0.292024    -0.032514  0.259510     0.733843         0.967486    -24.149486
2025-06-22 13:00:00  102746.00  102810.28  100327.46  100865.66  3718.17394  101636.965  102136.965    103977.9925     104475.960    101420.70            -500.000                   81.760         103977.9925          104475.960      -1 -0.046744 -0.338768    -0.032514  0.306254     0.699540         0.967486    -27.695053

In [10]:
import plotly.graph_objects as go
import plotly.offline as pyo
fig= go.Figure()

In [13]:
# plot ohlc candles for btcusdt

fig.add_trace(go.Candlestick(
    x= data.index,
    open= data["open"],
    high= data["high"],
    low= data["low"],
    close= data["close"],
    name= "BTCUSDT OHLC"))

#Ichimoku Lines
fig.add_trace(go.Scatter(x=data.index, y=data['tenkan_sen'], line=dict(color='blue'), name='Tenkan Sen'))
fig.add_trace(go.Scatter(x=data.index, y=data['kijun_sen'], line=dict(color='purple'), name='Kijun Sen'))
fig.add_trace(go.Scatter(x=data.index, y=data['senkou_span_a'], line=dict(color='green'), name='Senkou Span A', fill=None))
fig.add_trace(go.Scatter(x=data.index, y=data['senkou_span_b'], line=dict(color='red'), name='Senkou Span B', fill='tonexty', fillcolor='rgba(50,200,50,0.2)'))
fig.add_trace(go.Scatter(x=data.index, y=data['chikou_span'], line=dict(color='orange'), name='Chikou Span'))

# Mark Buy Signals
buy_signals = data[data['signal'] == 1]
fig.add_trace(go.Scatter(mode='markers', x=buy_signals.index, y=buy_signals['close'],
                         marker=dict(color='green', size=10, symbol='triangle-up'),
                         name='Buy Signal'))

# Mark Sell Signals
sell_signals = data[data['signal'] == -1]
fig.add_trace(go.Scatter(mode='markers', x=sell_signals.index, y=sell_signals['close'],
                         marker=dict(color='red', size=10, symbol='triangle-down'),
                         name='Sell Signal'))


# Update Layout
fig.update_layout(
    title="Ichimoku Trading Strategy Visualization",
    xaxis_title="Date",
    yaxis_title="Price",
    legend_title="Legend",
    width=1200,
    height=600
)

pyo.plot(fig, filename= "ichimoku.html")

'ichimoku.html'